### ISSUE TITLE
Failure showing up of corresponding subtitle  when click in sidebar

### ISSUE THREAD

**Issue by Kateliuxue** [initiumlab/initiumlab.com#39]
![default](https://cloud.githubusercontent.com/assets/14042060/9924673/45e5c85c-5d34-11e5-898a-507aba05c918.jpg)

**Comment by Kateliuxue** [comment]
After checking with Frank, it should be a problem of  wrong alignment.

**Comment by andyshuxin** [comment]
I think I fixed this with commit https://github.com/initiumlab/hexo-theme-next/commit/f720c89938473167a1005fba286b99ddcc286563

Can you confirm?

**Comment by frankinit** [comment]
Better now. But clicking the last subtitle on sidebar "5. 展望：數據新聞無障礙" still cannot lead to exact right place.

And, when zoom out to 90% or smaller, clicking the last subtitle does not change its color to blue.

Further more, when zoom out to 67% or smaller, same thing happens on the second last subtitle "4. 數據可觸化“.

**Comment by Kateliuxue** [comment]
The alignment works well with chrome on my computer (windows 8.1 chrome), but not on Firefox browser.

**Comment by andyshuxin** [comment]
@Kateliuxue @frankinit How about now? I've changed the algorithm to calculate height offset. You probably will see different spaces above the headings when you jump to them.

**Comment by Kateliuxue** [comment]
All works well: on Windows 8.1,  Chrome 43.0, Firefox & IE 11.

**Comment by frankinit** [comment]
@andyshuxin good on ordinary case! When zoom out to 75% or smaller, the last subtitle still doesn't work, though I think few user would do that.
Chrome 45, OS X 10.10.5.

**Comment by andyshuxin** [comment]
@frankinit That is because the offset is calculated in absolute px unit, which breaks when the base size changes. Let's leave this issue open and I'll work on a more comprehensive solution later.

**Comment by andyshuxin** [comment]
@frankinit Modified the title to reflect on the status quo.

**Comment by andyshuxin** [comment]
"Zooming" can't be easily monitored:
http://stackoverflow.com/questions/1713771/how-to-detect-page-zoom-level-in-all-modern-browsers

In some browsers, zooming triggers "resize", which mean the fix for resize could potentially also solve this issue:
https://github.com/initiumlab/hexo-theme-next/commit/18b7a346fe509e872a1562c272291ab165b0a116
